#!/bin/bash

function installNodeModules() {
	echo
	if [ -d node_modules ]; then
		echo "============== node modules installed already ============="
	else
		echo "============== Installing node modules ============="
		npm install
	fi
	echo
}

installNodeModules

# Start Fabric V1 WebAPIServer 
export PORT=4000
node app &
