#!/bin/bash

jq --version > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "Please Install 'jq' https://stedolan.github.io/jq/ to execute this script"
	echo
	exit 1
fi
starttime=$(date +%s)

echo ""
echo "Peer Node        : Peer$1"
echo "Chaincode Id     : $2"
echo "Chaincode Version: $3"
echo "Chaincode Path   : $4"
echo "Init Args:        : $5"
echo 'Init Args format >> "args":["a","100","b","200"]'

echo "POST request Enroll on Org1  ..."
echo
ORG1_TOKEN=$(curl -s -X POST \
  http://localhost:4000/users \
  -H "cache-control: no-cache" \
  -H "content-type: application/x-www-form-urlencoded" \
  -d 'username=7comm&orgName=org1')
echo $ORG1_TOKEN
ORG1_TOKEN=$(echo $ORG1_TOKEN | jq ".token" | sed "s/\"//g")
echo
echo "ORG1 token is $ORG1_TOKEN"
echo
echo "POST request Enroll on Org2 ..."
echo
ORG2_TOKEN=$(curl -s -X POST \
  http://localhost:4000/users \
  -H "cache-control: no-cache" \
  -H "content-type: application/x-www-form-urlencoded" \
  -d 'username=Innova7&orgName=org2')
echo $ORG2_TOKEN
ORG2_TOKEN=$(echo $ORG2_TOKEN | jq ".token" | sed "s/\"//g")
echo
echo "ORG2 token is $ORG2_TOKEN"
echo

if [ $1 -eq 0  ] ; then
  ORG="Org1"
  ORG_TOKEN = $ORG1_TOKEN
  PORT="7051"
fi
if [ $1 -eq 1  ] ; then
  ORG="Org1"
  ORG_TOKEN = $ORG1_TOKEN
  PORT="7056"
fi
if [ $1 -eq 2 ] ; then
  ORG="Org2"
  ORG_TOKEN = $ORG2_TOKEN
  PORT="8051"
fi
if [ $1 -eq 3 ] ; then
  ORG="Org2"
  ORG_TOKEN = $ORG2_TOKEN
  PORT="8056"
fi

echo
echo "POST instantiate chaincode on peer$1 of $ORG"
echo
curl -s -X POST \
  http://localhost:4000/channels/mychannel/chaincodes \
  -H "authorization: Bearer $ORG_TOKEN" \
  -H "cache-control: no-cache" \
  -H "content-type: application/json" \
  -H "x-access-token: $ORG_TOKEN" \
  -d '{
	"peers": ["localhost:$PORT"],
	"chaincodeName":"$2",
	"chaincodePath":"$4",
	"chaincodeVersion":"$3",
	"functionName":"init",
	"$4"
}'

echo
echo
echo "Total execution time : $(($(date +%s)-starttime)) secs ..."